### ISSUE TITLE
I modify the extractor code for python3&&ida>7.4(test in 7.7)

### ISSUE THREAD

**Issue by true-zk** [Yunlongs/Genius#4]
Python2 and ida6.8, ida 7.0 are less used nowadays. BTW, the search-engine in ur repo runs in python3. The version diff add probems to use. So I modify the extractor code for python3 and ida7.7 (there is big diff in api between ida7.0 and 7.7). 
Let me know if I can push my code.

**Comment by true-zk** [comment]
Hi, I make a pull request. u can check it.

**Comment by Yunlongs** [comment]
@true-zk  Wow! Amazing thanks! Your code is essential to this repository.  I will review your code in the next several days and then merge your PR. 

Thanks for your code again.
